services:
  hello-cpp-ubuntu-dev:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    image: hello-cpp-ubuntu-dev:latest  # 构建后镜像的名称和标签
    environment:
      SERVICE: hello-cpp-development-env
    volumes:
      - .:/root/hello-cpp
    working_dir: /root/hello-cpp
    # sleep infinity 用于保持容器运行，否则 vscode 无法进入容器，建议写在 .devcontainer/docker-compose.yml 文件中
    command: sleep infinity